version: '3.8'

services:
  buddy:
    image: ghcr.io/pteranodon/buddy:latest
    restart: always
    networks:
      - buddy0
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pteranodon
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pteranodon/:/etc/pteranodon/"
      - "/var/lib/pteranodon/:/var/lib/pteranodon/"
      - "/var/log/pteranodon/:/var/log/pteranodon/"
      - "/tmp/pteranodon/:/tmp/pteranodon/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

networks:
  buddy0:
    name: buddy0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: buddy0
